# Generated by Django 5.2.16 on 2026-08-04 06:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=10)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_high_bp', models.BooleanField(default=False)),
                ('has_pcod_pcos', models.BooleanField(default=False)),
                ('has_skin_allergy', models.BooleanField(default=False)),
                ('has_keloid_history', models.BooleanField(default=False)),
                ('other_medical_history', models.TextField(blank=True, null=True)),
                ('treatment_area', models.CharField(blank=True, max_length=255, null=True)),
                ('hair_type', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('photographs_taken', models.BooleanField(default=False)),
                ('custom_clinical_fields', models.JSONField(blank=True, default=dict)),
                ('inst_spf_sunscreen', models.BooleanField(default=False)),
                ('inst_no_waxing_threading', models.BooleanField(default=False)),
                ('inst_avoid_hot_water_steam', models.BooleanField(default=False)),
                ('inst_use_moisturizer', models.BooleanField(default=False)),
                ('inst_attend_next_session', models.BooleanField(default=False)),
                ('custom_post_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('session_no', models.IntegerField()),
                ('total_sessions_in_package', models.IntegerField(default=1)),
                ('treatment_given', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('before_photo', models.TextField(blank=True, null=True)),
                ('after_photo', models.TextField(blank=True, null=True)),
                ('amount_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Online', 'Online')], default='Cash', max_length=20)),
                ('next_appointment_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
                ('staff_attended', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_attended', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-id'],
            },
        ),
    ]
