# Generated by Django 5.2.16 on 2026-08-12 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_age_alter_patient_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
