# Generated by Django 5.2.16 on 2026-08-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='batch',
            field=models.CharField(blank=True, default='Morning Batch (10:00 - 13:00)', max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='admission',
            name='course',
            field=models.CharField(blank=True, default='Professional Makeup & Hairstyling Diploma', max_length=255),
        ),
        migrations.AlterField(
            model_name='admission',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
