# Generated by Django 5.2.16 on 2026-08-12 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_admission_batch_alter_admission_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
