# Generated by Django 5.2.16 on 2026-08-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(blank=True, default='Skin & Laser', max_length=100),
        ),
    ]
