# Generated by Django 5.2.16 on 2026-08-04 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('Salon', 'Salon Services'), ('Makeup', 'Makeup Services')], max_length=20)),
                ('service_name', models.CharField(max_length=255)),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_mode', models.CharField(default='Cash', max_length=50)),
                ('staff_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
            ],
        ),
    ]
