# Generated by Django 5.2.16 on 2026-08-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonbooking',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salonbooking',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salonbooking',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Salon', 'Salon Services'), ('Makeup', 'Makeup Services')], default='Salon', max_length=20),
        ),
    ]
