# Generated by Django 5.2.16 on 2026-08-12 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_salonbooking_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonbooking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
